import Head from "next/head";
import { useSession, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-[#F5F5DC] h-full min-h-screen">
        <section className="max-w-7xl container mx-auto bg-grey-800 flex items-center justify-center">
          <h1 className="text-4xl font-bold leading-7 pt-20">
            Welcome to the Landing Page
          </h1>
        </section>
      </main>
    </div>
  );
}
